### PR TITLE
implement chunkhash && replace default [hash] with [chunkhash]

### PR DESCRIPTION
**Pull request by duxiaofeng-github**

### CODE REVIEW

**Comment by duxiaofeng-github** [comment]
Is there someone review this pr?

**Comment by jeerbl** [comment]
I'll review it in the evening. Thanks!

**Comment by duxiaofeng-github** [comment]
@jeerbl thx

**Comment by jeerbl** [comment]
Hi @duxiaofeng-github !

Is this still compatible with Webpack 2? Thank for the PR, I think it will solve issue #13.

Cheers,
Jerome

**Comment by duxiaofeng-github** [comment]
@jeerbl , it runs in my webpack 3 project normally. So I think it should be ok with webpack2 too. here is my webpack config:

` 
{
    test: /\.font\.(js|json)$/,
    use: [
      ...extractWebfontCssLoader,
      {
        loader: 'webfonts-loader',
        options: {
          fileName: 'assets/[chunkhash]-[fontname].[ext]'
        },
      },
    ],
  },
`

**Comment by duxiaofeng-github** [comment]
I face the same issue with #13. I implement chunkhash so that CDN can reusing cache.

**Pull request merged**
