### PR TITLE
Added html font preview generation

### PR DESCRIPTION
**Pull request by davorpeic**
I mapped few more features that https://github.com/sunflowerdeath/webfonts-generator has, and also did fallback options to avoid any issues with previous setup. 

If you notice anything please let me know and I can fix it.

### CODE REVIEW

**Comment by jeerbl** [comment]
Please fix the issues described in the build log before I can merge this.

**Comment by tarunRao** [comment]
Any updates? This preview feature looks useful.

**Comment by ovi1337** [comment]
@davorpeic can you fix the issues which are in the travis build log please?

**Comment by jeerbl** [comment]
Closing as no answer from opener.

**Comment by davorpeic** [comment]
Thanks all, pguimera made fixes, it looks like CI has some issues validating changes, you expect soon this to be merged I hope :)

**Pull request closed without merging**
